language: r
dist: bionic
latex: false
# pandoc_version: 2.7.3

cache:
  packages: true
  directories:
  - "$HOME/bin"
  - "$HOME/.fonts"
  - "$HOME/.TinyTex"
  - "$TRAVIS_BUILD_DIR/_bookdown_files"
  - "$HOME/.local/share/renv"
  - "$TRAVIS_BUILD_DIR/renv/library"

addons:
  ssh_known_hosts: pearson.tadaa-data.de:54321

apt_packages:
  - fonts-roboto
  - fonts-oflb-asana-math

before_install:
  - |
    # 1. Install TinyTex manually if not already in cache
    # Travis creates $HOME/.TinyTex if nonexistent, so we check bin subdir
    if [ ! -d $HOME/.TinyTex/bin ]; then
      Rscript -e "install.packages('tinytex')"
      Rscript -e "tinytex::install_tinytex()"
    fi

    mkdir -p $HOME/.fonts

    # 2. Check if fonts are present in cached .fonts dir, if not, download + install
    if [ ! -e $HOME/.fonts/gyre.zip ]; then
     wget http://www.gust.org.pl/projects/e-foundry/tex-gyre/pagella/qpl2_501otf.zip -O $HOME/.fonts/gyre.zip
     unzip $HOME/.fonts/gyre.zip -d $HOME/.fonts/
    fi

    if [ ! -e $HOME/.fonts/gyreheros.zip ]; then
     wget http://www.gust.org.pl/projects/e-foundry/tex-gyre/heros/qhv2.004otf.zip -O $HOME/.fonts/gyreheros.zip
     unzip $HOME/.fonts/gyreheros.zip -d $HOME/.fonts/
    fi

    if [ ! -e $HOME/.fonts/fira.zip ]; then
      wget https://github.com/bBoxType/FiraSans/archive/master.zip -O $HOME/.fonts/fira.zip
      unzip ~/.fonts/fira.zip '*.ttf' -d $HOME/.fonts/
    fi

    # 3. Copy fontconfig for possibly maybe xelatex font issue with spaces in font names
    cp $HOME/.TinyTeX/texmf-var/fonts/conf/texlive-fontconfig.conf ~/.fonts.conf

    # 4. Update font cache for previously installed fonts (+ list fonts for debugging)
    fc-cache -fv
    fc-list

install:
  - Rscript -e "renv::restore()"

before_script:
  - '[ -x "$HOME/bin/phantomjs" ] || Rscript -e "webshot::install_phantomjs()"'
  - Rscript -e "remotes::install_github('hrbrmstr/firasans')"

script:
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"

before_deploy:
  - openssl aes-256-cbc -K $encrypted_63ba58dddd47_key -iv $encrypted_63ba58dddd47_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  - provider: pages
    local_dir: poisson-regression
    skip_cleanup: true
    keep_history: true
    github_token: "$GITHUB_PAT"
    target_branch: gh-pages
  - provider: script
    skip_cleanup: true
    script: rsync -r --quiet $TRAVIS_BUILD_DIR/poisson-regression -e 'ssh -p 54321'
      travis@pearson.tadaa-data.de:/srv/poisson-regression
    on:
      branch: master

notifications:
  email:
    on_success: change
    on_failure: change
