sudo: false
language: r
cache:
  packages: yes
  directories:
    - $HOME/bin
    - $TRAVIS_BUILD_DIR/_bookdown_filespandoc_version: 1.19.2.1

before_script:
  - "tlmgr install fira"
  - "tlmgr install asana-math"
  - "tlmgr install tex-gyre"
  - "[ -x \"$HOME/bin/phantomjs\" ] || Rscript -e \"webshot::install_phantomjs()\""
  - chmod +x ./_build.travis.sh
  - chmod +x ./_deploy.sh


script:
  - ./_build.travis.sh
  - ./_deploy.sh

