sudo: false
language: r
cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_filespandoc_version: 1.19.2.1

before_script:
  - chmod +x ./_build.travis.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

