language: r
dist: bionic
latex: false
# pandoc_version: 2.7.3

cache:
  packages: true
  directories:
  - "$HOME/bin"
  - "$HOME/.local/share/fonts"
  - "$HOME/.TinyTex"
  - "$TRAVIS_BUILD_DIR/_bookdown_files"
  - "$HOME/.local/share/renv"
  - "$TRAVIS_BUILD_DIR/renv/library"

addons:
  ssh_known_hosts:
    secure: lQ09vWJHSXhLpfsYAras50R3TOEjdghX24d7dAmcAavlL9batt0qYSOJ++2oXyAU/z6BjeLpMF2U+MxBwhOaoDDYOXSpYbK8GoKU4msUr9GGzlyVJuX+Z5WggLLRzArwtc8cQRIsZPmnX1IaLD8dtLV3OJFVHj1xt0BDOuONse2AaY30y/koQQQzRfqQjPXyplEPX4NDRlH7+G33fH6RPqwHitSaEqtAuNCWsSK69c1S4JK/yOatn2QUVsQKRTiqZ5Cbi/nm+5MwrG2xRdDfoGOMN+z68IHVSjBTssyWKJ4pQ3aYC9vXRmbnQdqT+FBMhulQWcU/fCbY6nxhXj0LQmo4lbUGOiSUs6EwSQFjylXP+xck+XAUcnGDFbRU1ZIPNc18dlo9vkZd9jnw3dzkMs8AWRMGhKrc+HZRJ6kV7sFXHiRHntWzl79u7Pu7A1GE7IO+WdXSilGCbq6U5eMB/91RImV8KBrXO1CjyfiHaie/uxVYqN6KEix15/9ecmivsaTuvHbd0eiHfSQMXit9K9FD/kAxZtdd7ulAoyCGpKj8R9VoQSjVTxp01PJ6D1JJVazzncVsZ9QsfCm3qwtieEcjH/NBsgcp4I0pYBspWBjw6zKLWwK5iFC2X4d1/siIEO+6Vmnwap9YojZBsrNcDe46horgdWS26Cg9EyEq3BU=

apt_packages:
  - fonts-roboto
  - fonts-robot-slab
  - fonts-oflb-asana-math

before_install:
  - Rscript -e "renv::restore()"
  - |
    # 1. Install TinyTex manually if not already in cache
    # Travis creates $HOME/.TinyTex if nonexistent, so we check bin subdir
    if [ ! -d $HOME/.TinyTex/bin ]; then
      Rscript -e "tinytex::install_tinytex()"
    fi
  - mkdir -p $HOME/.local/share/fonts
  - "./get_fira_fonts.sh"
  - |
    # 3. Copy fontconfig for possibly maybe xelatex font issue with spaces in font names
    cp $HOME/.TinyTeX/texmf-var/fonts/conf/texlive-fontconfig.conf ~/.fonts.conf
  - |
    # 4. Update font cache for previously installed fonts (+ list fonts for debugging)
    fc-cache -fv
    fc-list

before_script:
  - '[ -x "$HOME/bin/phantomjs" ] || Rscript -e "webshot::install_phantomjs()"'

script:
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"

before_deploy:
  - openssl aes-256-cbc -K $encrypted_63ba58dddd47_key -iv $encrypted_63ba58dddd47_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  - provider: pages
    local_dir: poisson-regression
    skip_cleanup: true
    keep_history: true
    github_token: "$GITHUB_PAT"
    target_branch: gh-pages
  - provider: script
    skip_cleanup: true
    script: rsync -r --quiet $TRAVIS_BUILD_DIR/poisson-regression -e 'ssh -p 54321'
      travis@pearson.tadaa-data.de:/srv/poisson-regression
    on:
      branch: master

notifications:
  email:
    on_success: change
    on_failure: change
