sudo: false
language: r
dist: bionic
cache:
  packages: yes
  directories:
    - $HOME/bin
    - $TRAVIS_BUILD_DIR/_bookdown_files
#pandoc_version: 1.19.2.1

addons:
  apt:
    packages:
      - tex-gyre
      - fonts-oflb-asana-math

before_install:
  - "Rscript -e \"tinytex::install_tinytex()\""
#  - tlmgr install fira
#  - tlmgr install Asana-Math
#  - tlmgr install tex-gyre

before_script:
  - "[ -x \"$HOME/bin/phantomjs\" ] || Rscript -e \"webshot::install_phantomjs()\""
#  - chmod +x ./_deploy.sh


script:
  - "Rscript -e \"bookdown::render_book('index.Rmd', 'bookdown::gitbook')\""
  - "Rscript -e \"bookdown::render_book('index.Rmd', 'bookdown::pdf_book')\""
#  - ./_deploy.sh

deploy:
  provider: pages
  local_dir: poisson-reg
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_PAT
  target_branch: gh-pages
