sudo: false
language: r
dist: bionic
latex: false
cache:
  packages: yes
  directories:
    - $HOME/bin
    - $HOME/.fonts
    - $HOME/.TinyTex
    - $TRAVIS_BUILD_DIR/_bookdown_files
#pandoc_version: 1.19.2.1


apt_packages:
# - tex-gyre
  - fonts-oflb-asana-math

before_install:
  - |
   Rscript -e "install.packages('tinytex')"
   Rscript -e "tinytex::install_tinytex()"

   if [ ! -d $HOME/.fonts ]; then
    mkdir $HOME/.fonts

    if [ ! -e $HOME/.fonts/gyre.zip ]; then
     wget http://www.gust.org.pl/projects/e-foundry/tex-gyre/pagella/qpl2_501otf.zip -O $HOME/.fonts/gyre.zip
     unzip $HOME/.fonts/gyre.zip -d $HOME/.fonts/
    fi

    if [ ! -e $HOME/.fonts/gyreheros.zip ]; then
     wget http://www.gust.org.pl/projects/e-foundry/tex-gyre/heros/qhv2.004otf.zip -O $HOME/.fonts/gyreheros.zip
     unzip $HOME/.fonts/gyreheros.zip -d $HOME/.fonts/
    fi

    if [ ! -e $HOME/.fonts/fira.zip ]; then
      wget https://github.com/bBoxType/FiraSans/archive/master.zip -O $HOME/.fonts/fira.zip
      unzip ~/.fonts/fira.zip '*.ttf' -d $HOME/.fonts/
    fi
   fi

   cp $HOME/.TinyTeX/texmf-var/fonts/conf/texlive-fontconfig.conf ~/.fonts.conf
   fc-cache -fv
   fc-list


before_script:
  - "[ -x \"$HOME/bin/phantomjs\" ] || Rscript -e \"webshot::install_phantomjs()\""
#  - chmod +x ./_deploy.sh


script:
  - "Rscript -e \"bookdown::render_book('index.Rmd', 'bookdown::gitbook')\""
  - "Rscript -e \"bookdown::render_book('index.Rmd', 'bookdown::pdf_book')\""
#  - ./_deploy.sh

deploy:
  provider: pages
  local_dir: poisson-regression
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_PAT
  target_branch: gh-pages

notifications:
  email: false
