---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Einführug {#intro}

- Anwendungsfall: Count data
- Regulärer Ansatz: Poisson-Regression
   - Major pitfall: Notwendigkeit für $\lambda_i = \mathbb{E}(y_i) = \mathrm{Var}(y_i)$
   - -> In der Regel overdispersion $\mathrm{Var}(y_i) > \mathbb{E}(y_i)$
   - Auch möglich: *under*dispersion $\mathrm{Var}(y_i) < \mathbb{E}(y_i)$
- "Lösung" für overdispersion: Negative Binomialverteilung
   - Modelliert die Varianz mit (als Gamma-verteilte Zufallsvariable, "Poisson-Gamma mixture")
   - Problem: Dispersionsparameter ist streng positiv, i.e. underdispersion kann nicht damit abgebildet werden
- "Lösung" für underdispersion:
   - Im Allgemeinen [generalized Poisson](https://stats.stackexchange.com/a/237177/80056) (R: [`VGAM`](https://rdrr.io/cran/VGAM/man/genpoisson.html))

# Annahmen und Abwandlungen

Es gelten Standardannahmen des GLM:

- $Y$ kommt aus der Exponentialfamilie (Normal-, Poisson-, Gamma-, Binomialverteilung)
- $\eta_i$ als linearer Operator
- Response- und Linkfunktionen $h(x)$ und $g(x) = h^{-1}(x)$

## Truncation und Censoring {#trunc_cens}

- **Truncation**: Bestimmte counts *nicht möglich*
  - z.B. keine Counts < 5 möglich -> *left truncation* (*right truncation* analog)
  - Interval truncation: Nur counts in Intervall $[a, b]$
- **Censoring**: Bestimmte counts *nicht beobachtet*, aber möglich

## Dispersion

### Overdispersion

### Underdispersion

## Zeros

### Zero Inflation

Problem: "Excess zeros", i.e. die gewählte Dichtefunktion sagt für $P(y_i\ |\ x_i = 0)$ eine deutlich kleinere Wahrscheinlichkeit vor, als in gegebenen Daten tatsächlich vorliegen.

Modellierung via "two part hurdle or a mixture model" [@hilbeModelingCountData2014, p. 19]

- Zero-inflated poisson (ZIP)
- Zero-inflated negative binomial (ZINB)
- Zero-inflated Poisson Inverse Gaussian (ZPIG)


"Hurdle models" in zwei Komponenten:

1. Binary 0,1 response, logit oder probit
   - Modellierung der Wahrscheinlichkeit für die non-zero counts
2. Zero-truncated count model

Zero-inflated models (mixture models):
- Auch: Logit/Probit Komponente für zeros
   - Unterschied: Modelliert Nullen im Gegensatz zu Einsen
- Binary zeros und count zeros werden durch beide Komponenten modelliert 
   - -> Nicht getrennt interpretierbar

Beispiel: Poisson-logit hurdle Modell, bestehend aus logit-Modell für zeros und zero-truncated Poisson für die non-zero counts

### Zero Truncation

Wenn die Beobachtungen keine Nullen enthalten bzw. im Modell nicht möglich sind, können *zero-truncated* (ZT) Modelle verwendet werden.

# Modelle 

Ein Überblick einiger Modelle mit parametrisierter Varianz (nach @hilbeModelingCountData2014, p. 12).

```{r models_table_1, echo=FALSE}
tibble::tribble(
  ~Model,                         ~Mean,  ~Variance,
  "Poisson",                     "$\\mu$", "$\\mu$",
  "Negative Binomial (NB1)",     "$\\mu$", "$\\mu (1 + \\alpha) = \\mu + \\alpha\\mu$",
  "Negative Binomial (NB2)",     "$\\mu$", "$\\mu (1 + \\alpha\\mu) = \\mu + \\alpha\\mu^2$",
  "Poisson Inverse Gamma (PIG)", "$\\mu$", "$\\mu (1 + \\alpha\\mu^2) = \\mu + \\alpha\\mu^3$",
  "Negative binomial-P",         "$\\mu$", "$\\mu (1 + \\alpha\\mu^p) = \\mu + \\alpha\\mu^p$",
  "Generalized Poisson",         "$\\mu$", "$\\mu (1 + \\alpha\\mu)^2 = \\mu + 2\\alpha\\mu^3 + \\alpha^2\\mu^3$"
 ) %>%
  kable(booktabs = TRUE, escape = FALSE) %>%
  kable_styling(position = "center", protect_latex = TRUE)
```


## Poisson {#mod_pois}

Eine Poisson-verteilte Zufallsvariable $Y \sim \mathrm{Poi}(\lambda)$ hat die Dichte

\begin{equation}
f(y\ |\ \lambda) = \mathrm{P}(Y = y) = \frac{\lambda^y \exp(-\lambda)}{y!} \quad, y \in \mathbb{N}_0
\end{equation}

Die Rate $\lambda_i = \mathbb{E}(y_i | x_i)$ der Poissonverteilung wird in der Regel log-linear modelliert als

\begin{equation}
\log(\lambda_i) = \eta_i = \mathbf{x}_i' \boldsymbol{\beta} = \beta_0 + \beta_1 x_1 + \ldots + \beta_k x_{ik}
\end{equation}

mit der regulären Form:

\begin{equation}
\lambda_i = \exp(\eta_i) = \exp(\beta_0) \cdot \exp(\beta_1 x_1) \cdot \ldots \cdot \exp(\beta_k x_k)
\end{equation}

Die lineare Verknüpfung

\begin{equation}
\lambda_i = \eta_i = \mathbf{x}_i' \boldsymbol{\beta}
\end{equation}

existiert auch für den Fall einer additiven Verknüpfung der Kovariablen, führt allerdings zu Restriktionen für $\boldsymbol{\beta}$, da $\mathbf{x}_i' \boldsymbol{\beta} \geq 0$ gelten muss 
Vgl. @fahrmeirRegressionModelleMethoden2009


### Annahmen

Primäre Annahme für Poisson-Modelle: *Equidispersion*, i.e. für den Parameter der Poissonverteilung gilt 

```{definition, name = "Equidispersion"}
\begin{equation}
\lambda_i = \mathbb{E}(y_i) = \mathrm{Var}(y_i)
\end{equation}
```

1. Die Abhängige / Zielvariable $Y$ muss eine Zählung sein.
2. $y \in \mathbb{N}_0$, insbesondere: $Y$ muss 0 enthalten können (siehe auch [Truncation und Censoring](#trunc_cens))
3. Beobachtungen sind unabhängig.
4. 
5. Erwartungswert und Varianz sind identisch (*equidispersion*), i.e. ein größerer Erwartungswert impliziert auch eine größere Varianz.
6. Die $\chi^2$-Statistik hat einen Wert nahe 1, i.e. beobachtete und erwartete Varianzen der response sind gleich


## Negative Binomial (NBIN) {#mod_nbin}

- Derivation: Poisson-Gamma Mischmodell
- Erweiterung der Poissonverteilung um einen Dispersionsparameter $\alpha$
  - Wenn $\alpha > 0$: overdispersion
  - Wenn $\alpha = 0$: Äquivalent zu Poisson
- Zwei Varianten: NB1, NB2
- Software Pitfalls:
  - Dispersionsparameter in R's `glm` bzw. `MASS::glm.nb` invertiert: $\theta = \frac 1 \alpha$
  - -> Äquivalenz zu Poisson bei $\theta \to \infty$
  
> "The negative binimial model adjusts for Poisson overdispersion; it cannot be used to model underdispersed Poisson data" 
> [@hilbeModelingCountData2014, p. 11]
  
  
Vgl @hilbeModelingCountData2014

## Poisson Inverse Gaussian (PIG) {#mod_pig}

- Annahme: Overdispersion besser über *inverse Gaussian* Verteilung als Gamma-Verteilung (siehe NBIN) beschreibbar

- Dispersionsparameter $\alpha$, Interpretation analog NBIN

- Software:
- R: `gamlss` (CRAN)
- Stata: `pigreg` ()

## Negative binomial-P (NB-P)

- NBIN: Varianz statisch für alle Beobachtungen
- -> NB-P: Varianz kann für Beobachtungen variieren (Parameter $\rho$)

- Primärer Anwendungsfall: Bestimmen, ob NB1 oder NB2 besser passt
  - Wenn $\rho \approx 2$ -> NB2, sonst NB1 (@hilbeModelingCountData2014, p. 21)

## Generalized Poisson {#mod_gp}

- Auch mit dispersion/scale Parameter $\alpha$
- Analog NBIN: $\alpha = 0 \Rightarrow y \sim \mathrm{Pois}(\lambda)$
- Selling feature: $\alpha < 0$ ist möglich, im Gegensatz zu NBIN
- -> Underdispersion modellierbar

- Software: 
- [Vgl. Stackexchange Kommentar von Joseph Hilbe](https://stats.stackexchange.com/a/237177/80056)
- R: [`VGAM`](https://rdrr.io/cran/VGAM/man/genpoisson.html)

## Heterogenous Negative Binomial (NBH) {#mod_nbh}

- Selling feature: Erlaubt Parametrisierung von $\alpha$
- -> Ursache für under-/overdispersion modellierbar
