# (APPENDIX) Appendix {-} 

# Ergänzungen

Hier finden sich Erläuterungen zu Themen, die nur tangentiell in Verbindung mit dem eigentlichen Thema stehen, aber unter Umständen dennoch von Interesse sein könnten.

## Missing values und missingness patterns {#appendix-missingness}

Zu den Begriffen im Kontext von missingness wird folgende Unterscheidung bezüglich der Verteilung der missing values für eine Variable $Y$ gemacht (vgl. auch @littleStatisticalAnalysisMissing2002, p. 12):

- **MCAR** (missing completely at random): Das Fehlen eines Wertes in $Y$ ist völlig unabhängig von sowohl beobachteten als auch unbeobachtet Daten. Dieser Fall wäre der idealzustand, ist allerdings in der Regel weder realistisch noch verifizierbar.
- **MAR** (missing at random): Es gibt einen Zusammenhang zwischen Ausfallwahrscheinlichkeit und *beobachteten* Daten. Das heißt auch, dass missingness durch beobachtete Daten erklärt werden kann, weshalb dieser Fall noch akzeptabel wäre.
- **MNAR** / **NMAR** (missing not at random): Weder *MCAR* noch *MAR* – die Ausfallwahrscheinlichkeit hängt von *unbeobachten* Daten ab. Das heißt, es gibt ein Ausfallmuster in $Y$, das nicht durch vorliegende Daten erklärt werden kann, wodurch in der Regel verzerrte Effektschätzungen entstehen.

# Reproduzierbarkeit {#repro}

Included for posterity and/or debugging purposes.

```{r sessioninfo, echo=FALSE}
sinfo <- sessioninfo::session_info()[c("platform", "packages")]

sinfo$platform %>% 
  unclass() %>% 
  as_tibble() %>% 
  t() %>% 
  as_tibble(rownames = "m", .name_repair = make.names) %>%
  setNames(c("Umgebungsvariable", "Wert")) %>%
  kable(booktabs = TRUE, linesep = "") %>%
  kable_styling(position = "center")

sinfo$packages %>%
  filter(attached) %>%
  select(package, loadedversion, source) %>%
  setNames(c("Package", "Version", "Quelle")) %>%
  kable(booktabs = TRUE, linesep = "") %>%
  kable_styling(position = "center")
```

