<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de-DE" xml:lang="de-DE">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3.6 Zero-Inflated Models (mixture models) | Poisson-Regression und ihre Leiden</title>
  <meta name="description" content="Because count data is hard" />
  <meta name="generator" content="bookdown 0.14 and GitBook 2.6.7" />

  <meta property="og:title" content="3.6 Zero-Inflated Models (mixture models) | Poisson-Regression und ihre Leiden" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="includes/images/poiscovr-orly.png" />
  <meta property="og:description" content="Because count data is hard" />
  <meta name="github-repo" content="jemus42/poisson-regression" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3.6 Zero-Inflated Models (mixture models) | Poisson-Regression und ihre Leiden" />
  
  <meta name="twitter:description" content="Because count data is hard" />
  <meta name="twitter:image" content="includes/images/poiscovr-orly.png" />

<meta name="author" content="Lukas Burk" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="diagnostische-modelle.html"/>
<link rel="next" href="anwendung.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<script src="libs/viz-0.3/viz.js"></script>
<link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="libs/grViz-binding-1.0.1/grViz.js"></script>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    "HTML-CSS": { fonts: ["Asana-Math"] },
    MathMenu: { showFontMenu: true },
    menuSettings: { zoom: "Click" }
  });
</script>
<link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Condensed|Roboto+Slab&display=swap" rel="stylesheet">


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="includes/css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Poisson Regression</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Einführung</a><ul>
<li class="chapter" data-level="1.1" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>1.1</b> Beispieldaten</a></li>
<li class="chapter" data-level="1.2" data-path="software-funs.html"><a href="software-funs.html"><i class="fa fa-check"></i><b>1.2</b> Verwendete Software</a><ul>
<li class="chapter" data-level="1.2.1" data-path="software-funs.html"><a href="software-funs.html#r-packages"><i class="fa fa-check"></i><b>1.2.1</b> R-Packages</a></li>
<li class="chapter" data-level="1.2.2" data-path="software-funs.html"><a href="software-funs.html#helperfuns"><i class="fa fa-check"></i><b>1.2.2</b> Funktionen</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="poisson-modell.html"><a href="poisson-modell.html"><i class="fa fa-check"></i><b>2</b> Das Poisson-Modell</a><ul>
<li class="chapter" data-level="2.1" data-path="annahmen.html"><a href="annahmen.html"><i class="fa fa-check"></i><b>2.1</b> Annahmen</a></li>
<li class="chapter" data-level="2.2" data-path="dispersion.html"><a href="dispersion.html"><i class="fa fa-check"></i><b>2.2</b> Dispersion</a><ul>
<li class="chapter" data-level="2.2.1" data-path="dispersion.html"><a href="dispersion.html#overdispersion"><i class="fa fa-check"></i><b>2.2.1</b> Overdispersion</a></li>
<li class="chapter" data-level="2.2.2" data-path="dispersion.html"><a href="dispersion.html#underdispersion"><i class="fa fa-check"></i><b>2.2.2</b> Underdispersion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="multiparam.html"><a href="multiparam.html"><i class="fa fa-check"></i><b>3</b> Mehrparametrische Modelle</a><ul>
<li class="chapter" data-level="3.1" data-path="mod-nb.html"><a href="mod-nb.html"><i class="fa fa-check"></i><b>3.1</b> Negativ Binomial (NB)</a></li>
<li class="chapter" data-level="3.2" data-path="mod-pig.html"><a href="mod-pig.html"><i class="fa fa-check"></i><b>3.2</b> Poisson Inverse Gaussian (PIG)</a></li>
<li class="chapter" data-level="3.3" data-path="mod-gp.html"><a href="mod-gp.html"><i class="fa fa-check"></i><b>3.3</b> Generalized Poisson (GP)</a></li>
<li class="chapter" data-level="3.4" data-path="mod-comp.html"><a href="mod-comp.html"><i class="fa fa-check"></i><b>3.4</b> Conway-Maxwell Poisson (COMP)</a></li>
<li class="chapter" data-level="3.5" data-path="diagnostische-modelle.html"><a href="diagnostische-modelle.html"><i class="fa fa-check"></i><b>3.5</b> Diagnostische Modelle</a><ul>
<li class="chapter" data-level="3.5.1" data-path="diagnostische-modelle.html"><a href="diagnostische-modelle.html#mod-nbh"><i class="fa fa-check"></i><b>3.5.1</b> Heterogenous Negative Binomial (NBH)</a></li>
<li class="chapter" data-level="3.5.2" data-path="diagnostische-modelle.html"><a href="diagnostische-modelle.html#mod-nbp"><i class="fa fa-check"></i><b>3.5.2</b> Negative binomial-P (NB-P)</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="mod-zi.html"><a href="mod-zi.html"><i class="fa fa-check"></i><b>3.6</b> Zero-Inflated Models (<em>mixture models</em>)</a><ul>
<li class="chapter" data-level="3.6.1" data-path="mod-zi.html"><a href="mod-zi.html#interpretation"><i class="fa fa-check"></i><b>3.6.1</b> Interpretation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="anwendung.html"><a href="anwendung.html"><i class="fa fa-check"></i><b>4</b> Anwendung</a><ul>
<li class="chapter" data-level="4.1" data-path="overdisp-diag.html"><a href="overdisp-diag.html"><i class="fa fa-check"></i><b>4.1</b> Overdispersion: Erkennung und Handhabung</a><ul>
<li class="chapter" data-level="4.1.1" data-path="overdisp-diag.html"><a href="overdisp-diag.html#lagrange-mulitplier-test"><i class="fa fa-check"></i><b>4.1.1</b> Lagrange Mulitplier Test</a></li>
<li class="chapter" data-level="4.1.2" data-path="overdisp-diag.html"><a href="overdisp-diag.html#boundary-likelihood-ratio-test-blr"><i class="fa fa-check"></i><b>4.1.2</b> (Boundary) Likelihood Ratio Test (BLR)</a></li>
<li class="chapter" data-level="4.1.3" data-path="overdisp-diag.html"><a href="overdisp-diag.html#umgang-mit-overdispersion"><i class="fa fa-check"></i><b>4.1.3</b> Umgang mit Overdispersion</a><ul>
<li class="chapter" data-level="4.1.3.1" data-path="overdisp-diag.html"><a href="overdisp-diag.html#sandwich"><i class="fa fa-check"></i><b>4.1.3.1</b> Robuste Varianzschätzer (Sandwich Estimators)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="zeros.html"><a href="zeros.html"><i class="fa fa-check"></i><b>4.2</b> Zero-Inflation (ZI)</a><ul>
<li class="chapter" data-level="4.2.1" data-path="zeros.html"><a href="zeros.html#zi-compare"><i class="fa fa-check"></i><b>4.2.1</b> Vergleich von Zero-Inflated models</a></li>
<li class="chapter" data-level="4.2.2" data-path="zeros.html"><a href="zeros.html#zi-modelling"><i class="fa fa-check"></i><b>4.2.2</b> Modellierung</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="entscheidungshilfen.html"><a href="entscheidungshilfen.html"><i class="fa fa-check"></i><b>5</b> Entscheidungshilfen</a></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="verfügbarkeit.html"><a href="verfügbarkeit.html"><i class="fa fa-check"></i><b>A</b> Verfügbarkeit</a></li>
<li class="chapter" data-level="B" data-path="ergänzungen.html"><a href="ergänzungen.html"><i class="fa fa-check"></i><b>B</b> Ergänzungen</a><ul>
<li class="chapter" data-level="B.1" data-path="appendix-missingness.html"><a href="appendix-missingness.html"><i class="fa fa-check"></i><b>B.1</b> Missing values und missingness patterns</a></li>
<li class="chapter" data-level="B.2" data-path="trunc-cens.html"><a href="trunc-cens.html"><i class="fa fa-check"></i><b>B.2</b> Truncation und Censoring</a></li>
<li class="chapter" data-level="B.3" data-path="mod-hurdle.html"><a href="mod-hurdle.html"><i class="fa fa-check"></i><b>B.3</b> Hurdle models</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="repro.html"><a href="repro.html"><i class="fa fa-check"></i><b>C</b> Reproduzierbarkeit</a><ul>
<li class="chapter" data-level="C.1" data-path="r-code.html"><a href="r-code.html"><i class="fa fa-check"></i><b>C.1</b> R-Code</a></li>
<li class="chapter" data-level="C.2" data-path="session-info.html"><a href="session-info.html"><i class="fa fa-check"></i><b>C.2</b> Session Info</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="unsorted.html"><a href="unsorted.html"><i class="fa fa-check"></i><b>D</b> Unsorted</a><ul>
<li class="chapter" data-level="D.1" data-path="general-advice.html"><a href="general-advice.html"><i class="fa fa-check"></i><b>D.1</b> General Advice</a></li>
<li class="chapter" data-level="D.2" data-path="beispiel-nach-hilbe-2014-p-211ff.html"><a href="beispiel-nach-hilbe-2014-p-211ff.html"><i class="fa fa-check"></i><b>D.2</b> Beispiel nach Hilbe (2014 p. 211ff)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="literatur.html"><a href="literatur.html"><i class="fa fa-check"></i>Literatur</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Built with bookdown</a></li>
<li><a href="https://git.tadaa-data.de/lukas/poisson-regression" target="blank">Source on Gitea</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Poisson-Regression und ihre Leiden</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="mod-zi" class="section level2">
<h2><span class="header-section-number">3.6</span> Zero-Inflated Models (<em>mixture models</em>)</h2>
<p>Zero-inflated Modelle sind <em>mixtures</em>, das heißt, sie entstehen durch Mischung zweier Wahrscheinlichkeitsfunktionen. In der Regel wird eine Nullverteilung mit einer regulären Zählverteilung (Poisson, NB, PIG, …) “gemischt”, abhängig von einem <em>mixture parameter</em> <span class="math inline">\(\pi \in [0,1]\)</span>, der z.B. logistisch modelliert wird. Die Nullen im Modell werden dementsprechend durch beide Verteilungen (Nullverteilung, Zählverteilung) beschrieben – im Gegensatz zu <em>hurdle models</em> (vgl. <a href="mod-hurdle.html#mod-hurdle">B.3</a>), die Nullen logistisch und die positiven counts über eine <em>truncated</em> distribution modellieren würden.</p>
<p>Zero-inflated distributions wie ZIP und ZINB wurden hergeleitet als zweiteilige mixture distributions. Die allgemeine Form für mixture distributions ist</p>

<div class="definition">
<p><span id="def:defmixture" class="definition"><strong>Definition 3.9  (Mixture distribution und zero-inflated distribution)  </strong></span><span class="math display">\[\begin{equation*}
  P(Y = y) = p \cdot g_1(y) + (1-p) \cdot g_2(y)
\end{equation*}\]</span></p>
<p>mit <span class="math inline">\(p\)</span> als <em>mixture proportion</em> und <span class="math inline">\(g_1, g_2\)</span> als Dichte-/Massefunktionen der beiden Komponenten.</p>
<p>Für zero-inflation setzt man <span class="math inline">\(p\)</span> als <em>rate of zero-inflation</em> <span class="math inline">\(\pi\)</span>, <span class="math inline">\(g_1\)</span> als degenerierten 0-Verteilung und <span class="math inline">\(g_2\)</span> als Poisson-PMF oder ähnliche Zähl-Verteilung wie NB, PIG, etc.</p>
<p>Eine alternative Darstellung für eine <em>zero-inflated</em> Verteilung (<a href="https://www.statistik.uni-dortmund.de/useR-2008/slides/Kleiber+Zeileis.pdf">siehe</a>):</p>
<p><span class="math display">\[\begin{equation*}
f_\mathrm{zeroinfl} (y; x, \beta, \pi) = \pi \cdot I_{\{0\}}(y) + (1 - \pi) \cdot f_{\mathrm{count}}(y; x, \beta)
\end{equation*}\]</span></p>
<p>Mit zu modellierendem Erwartungswert</p>
<p><span class="math display">\[\begin{equation*}
\mu_i = \pi_i \cdot 0 + (1 - \pi_i) \cdot \exp(x_i^T\beta)
\end{equation*}\]</span></p>
Wobei <span class="math inline">\(\pi\)</span> in der Regel binomial, bzw. mittels logistischer Regression geschätzt wird.
</div>

<p>Und im Speziellen, anhand der Beispiele ZIP und ZINB:</p>

<div class="definition">
<p><span id="def:defzip" class="definition"><strong>Definition 3.10  (Zero-Inflated Poisson Verteilung (ZIP))  </strong></span>Nach <span class="citation">Perumean-Chaney u. a. (<a href="#ref-perumean-chaneyZeroinflatedOverdispersedWhat2013" role="doc-biblioref">2013</a>)</span> (p. 1675)</p>
<span class="math display">\[\begin{align*}
P(Y = 0) &amp;= \pi + (1-\pi) \cdot e^{-\mu} \\
P(Y = y) &amp;= (1 - \pi) \cdot \frac{\mu^y e^{-\mu}}{y!}, \quad y = 1, 2, 3, \ldots
\end{align*}\]</span>
</div>


<div class="definition">
<p><span id="def:defzinb" class="definition"><strong>Definition 3.11  (Zero-Inflated Negative Binomialverteilung (ZINB))  </strong></span>Nach <span class="citation">Perumean-Chaney u. a. (<a href="#ref-perumean-chaneyZeroinflatedOverdispersedWhat2013" role="doc-biblioref">2013</a>)</span> (p. 1675)</p>
<span class="math display">\[\begin{align*}
P(Y = 0) &amp;= \pi + (1 - \pi) \cdot \frac{\theta^\theta}{(\theta + \mu)^\theta}  \\
P(Y = y) &amp;= (1 - \pi) \cdot \frac{\Gamma(\theta+y)}{\Gamma(\theta) \Gamma(y + 1)} \frac{\theta^\theta \mu^y}{(\theta + \mu)^{(\theta + y)}}, \quad y = 1, 2, 3, \ldots
\end{align*}\]</span>
</div>

<div id="interpretation" class="section level3">
<h3><span class="header-section-number">3.6.1</span> Interpretation</h3>
<p>Ein Anwendungsbeispiel der ZIP findet sich auf der Seite der UCLA (<a href="https://stats.idre.ucla.edu/sas/dae/zero-inflatedpoisson-regression/">SAS</a>, <a href="https://stats.idre.ucla.edu/r/dae/zip/">R</a>, zusätzlich gibt es einmal <a href="https://stats.idre.ucla.edu/sas/output/zero-inflated-poisson-regression/">annotated Output (SAS)</a>), wobei der <code>fish</code>-Datensatz verwendet wird.</p>
<p>In diesem Datensatz beobachten wir Nullen mit zwei unterschiedlichen Ursprüngen: Zum Einen haben wir die Nullen der Personen, die geangelt haben, aber keine Fische fingen – und zum Anderen haben wir die Nullen der Personen, die <em>nicht angelten</em>, und daher garantiert auch keine Fische fingen (“<em>certain zeros</em>”) (vgl. auch Abschnitt <a href="zeros.html#zi-modelling">4.2.2</a>).</p>
<p>Ein ZIP-Modell erlaubt uns hier also beide Komponenten zu berücksichtigen – sowohl die Personen, die erfolglos angelten, als auch die Personen, die gar nicht angelten.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="mod-zi.html#cb29-1"></a><span class="co"># ZP basierend auf fish-Daten, Modell aus UCLA-Tutorialseite</span></span>
<span id="cb29-2"><a href="mod-zi.html#cb29-2"></a>m_zip &lt;-<span class="st"> </span>pscl<span class="op">::</span><span class="kw">zeroinfl</span>(count <span class="op">~</span><span class="st"> </span>child <span class="op">+</span><span class="st"> </span>camper <span class="op">|</span><span class="st"> </span>persons, <span class="dt">data =</span> fish)</span>
<span id="cb29-3"><a href="mod-zi.html#cb29-3"></a></span>
<span id="cb29-4"><a href="mod-zi.html#cb29-4"></a><span class="kw">summary</span>(m_zip)</span></code></pre></div>
<pre><code>#&gt; 
#&gt; Call:
#&gt; pscl::zeroinfl(formula = count ~ child + camper | persons, data = fish)
#&gt; 
#&gt; Pearson residuals:
#&gt;     Min      1Q  Median      3Q     Max 
#&gt; -1.2369 -0.7540 -0.6080 -0.1921 24.0847 
#&gt; 
#&gt; Count model coefficients (poisson with log link):
#&gt;             Estimate Std. Error z value Pr(&gt;|z|)    
#&gt; (Intercept)  1.59789    0.08554  18.680   &lt;2e-16 ***
#&gt; child       -1.04284    0.09999 -10.430   &lt;2e-16 ***
#&gt; camper1      0.83402    0.09363   8.908   &lt;2e-16 ***
#&gt; 
#&gt; Zero-inflation model coefficients (binomial with logit link):
#&gt;             Estimate Std. Error z value Pr(&gt;|z|)    
#&gt; (Intercept)   1.2974     0.3739   3.470 0.000520 ***
#&gt; persons      -0.5643     0.1630  -3.463 0.000534 ***
#&gt; ---
#&gt; Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1 
#&gt; 
#&gt; Number of iterations in BFGS optimization: 12 
#&gt; Log-likelihood: -1032 on 5 Df</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="mod-zi.html#cb31-1"></a><span class="co"># Exponentierte Koeffizienten</span></span>
<span id="cb31-2"><a href="mod-zi.html#cb31-2"></a>tibble<span class="op">::</span><span class="kw">enframe</span>(<span class="kw">exp</span>(<span class="kw">coef</span>(m_zip)), <span class="dt">name =</span> <span class="st">&quot;coefficient&quot;</span>)</span></code></pre></div>
<div class="kable-table">

<table>
<thead>
<tr>
<th style="text-align:left;">
coefficient
</th>
<th style="text-align:right;">
value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
count_(Intercept)
</td>
<td style="text-align:right;">
4.9425841
</td>
</tr>
<tr>
<td style="text-align:left;">
count_child
</td>
<td style="text-align:right;">
0.3524526
</td>
</tr>
<tr>
<td style="text-align:left;">
count_camper1
</td>
<td style="text-align:right;">
2.3025648
</td>
</tr>
<tr>
<td style="text-align:left;">
zero_(Intercept)
</td>
<td style="text-align:right;">
3.6599163
</td>
</tr>
<tr>
<td style="text-align:left;">
zero_persons
</td>
<td style="text-align:right;">
0.5687312
</td>
</tr>
</tbody>
</table>
</div>
<p>Wir erhalten zwei Sets an Koeffizienten:</p>
<p><strong>Count-model</strong>: Das count model (<code>count_</code>), i.e. Poisson. Hier modellieren wir die Anzahl der gefangen Fische ohne Berücksichtigung der <em>excess zeros</em>. Diese Koeffizienten werden analog einer herkömmlichen Poisson-Regression interpretiert.</p>
<p><strong>Inflation-model</strong>: Die binomiale Komponente (<code>zeros_</code>) für die <em>excess zeros</em>, womit wir die Wahrscheinlichkeit von “certain zeros” modellieren. Diese Koeffizienten werden analog einer logistischen Regression interpretiert.<br />
Aus dem UCLA DAE:</p>
<blockquote>
<p><strong>persons</strong>: If a group were to increase its persons value by one, <strong>the odds that it would be in the “Certain Zero” group</strong> would decrease by a factor of exp(-0.5643) = 0.5687581. In other words, the more people in a group, the less likely the group is a certain zero.</p>
</blockquote>
<blockquote>
<p><strong>Intercept</strong>: If all of the predictor variables in the model are evaluated at zero, the odds of being a “Certain Zero” is exp(1.2974) = 3.659769. This means that the predicted odds of a group with zero persons is 3.659769 (though remember that evaluating persons at zero is out of the range of plausible values–every group must have at least one person).</p>
</blockquote>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="mod-zi.html#cb32-1"></a>nsim &lt;-<span class="st"> </span><span class="dv">10</span><span class="op">^</span><span class="dv">4</span></span>
<span id="cb32-2"><a href="mod-zi.html#cb32-2"></a>meansim &lt;-<span class="st"> </span><span class="dv">2</span></span>
<span id="cb32-3"><a href="mod-zi.html#cb32-3"></a></span>
<span id="cb32-4"><a href="mod-zi.html#cb32-4"></a>tibble<span class="op">::</span><span class="kw">tibble</span>(</span>
<span id="cb32-5"><a href="mod-zi.html#cb32-5"></a>  <span class="dt">counts =</span> <span class="kw">rpois</span>(<span class="dt">n =</span> nsim, <span class="dt">lambda =</span> meansim),</span>
<span id="cb32-6"><a href="mod-zi.html#cb32-6"></a>) <span class="op">%&gt;%</span></span>
<span id="cb32-7"><a href="mod-zi.html#cb32-7"></a><span class="st">  </span><span class="kw">count</span>(counts, <span class="dt">name =</span> <span class="st">&quot;Poisson&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb32-8"><a href="mod-zi.html#cb32-8"></a><span class="st">  </span><span class="kw">mutate</span>(</span>
<span id="cb32-9"><a href="mod-zi.html#cb32-9"></a>    <span class="dt">Zeros =</span> <span class="kw">floor</span>(Poisson<span class="op">/</span><span class="dv">2</span>),</span>
<span id="cb32-10"><a href="mod-zi.html#cb32-10"></a>    <span class="dt">Zeros =</span> <span class="kw">ifelse</span>(counts <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>, <span class="dv">0</span>, Zeros)</span>
<span id="cb32-11"><a href="mod-zi.html#cb32-11"></a>  ) <span class="op">%&gt;%</span></span>
<span id="cb32-12"><a href="mod-zi.html#cb32-12"></a><span class="st">  </span><span class="kw">gather</span>(source, freq, Poisson, Zeros) <span class="op">%&gt;%</span></span>
<span id="cb32-13"><a href="mod-zi.html#cb32-13"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">source =</span> forcats<span class="op">::</span><span class="kw">fct_rev</span>(source),</span>
<span id="cb32-14"><a href="mod-zi.html#cb32-14"></a>         <span class="dt">freq =</span> freq<span class="op">/</span>nsim) <span class="op">%&gt;%</span></span>
<span id="cb32-15"><a href="mod-zi.html#cb32-15"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> counts, <span class="dt">y =</span> freq, <span class="dt">fill =</span> source)) <span class="op">+</span></span>
<span id="cb32-16"><a href="mod-zi.html#cb32-16"></a><span class="st">  </span><span class="kw">geom_col</span>(<span class="dt">alpha =</span> <span class="fl">.75</span>) <span class="op">+</span></span>
<span id="cb32-17"><a href="mod-zi.html#cb32-17"></a><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">12</span>)) <span class="op">+</span></span>
<span id="cb32-18"><a href="mod-zi.html#cb32-18"></a><span class="st">  </span><span class="kw">scale_fill_brewer</span>(<span class="dt">palette =</span> <span class="st">&quot;Set1&quot;</span>, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="dt">Zeros =</span> <span class="st">&quot;Certain Zeros&quot;</span>, <span class="dt">Poisson =</span> <span class="st">&quot;Poisson-Modell&quot;</span>)) <span class="op">+</span></span>
<span id="cb32-19"><a href="mod-zi.html#cb32-19"></a><span class="st">  </span><span class="kw">labs</span>(</span>
<span id="cb32-20"><a href="mod-zi.html#cb32-20"></a>    <span class="dt">title =</span> <span class="st">&quot;Schaubild: Zero-Inflated Poisson&quot;</span>,</span>
<span id="cb32-21"><a href="mod-zi.html#cb32-21"></a>    <span class="dt">subtitle =</span> <span class="st">&quot;Nullen in den Daten: Certain zeros + count zeros&quot;</span>,</span>
<span id="cb32-22"><a href="mod-zi.html#cb32-22"></a>    <span class="dt">x =</span> <span class="st">&quot;Count&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Anteil an Gesamtsichtprobe&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb32-23"><a href="mod-zi.html#cb32-23"></a>    <span class="dt">caption =</span> <span class="st">&quot;Simulierte Daten&quot;</span></span>
<span id="cb32-24"><a href="mod-zi.html#cb32-24"></a>  ) <span class="op">+</span></span>
<span id="cb32-25"><a href="mod-zi.html#cb32-25"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;bottom&quot;</span>)</span></code></pre></div>
<p><img src="poisson-regression_files/figure-html/zi-principle-plot-1.png" width="768" style="display: block; margin: auto;" /></p>

</div>
</div>
<!-- </div> -->
<h3>Literatur</h3>
<div id="refs" class="references">
<div id="ref-perumean-chaneyZeroinflatedOverdispersedWhat2013">
<p>Perumean-Chaney, Suzanne E., Charity Morgan, David McDowall, und Inmaculada Aban. 2013. „Zero-Inflated and Overdispersed: What’s One to Do?“ <em>Journal of Statistical Computation and Simulation</em> 83 (9): 1671–83. <a href="https://doi.org/10.1080/00949655.2012.668550">https://doi.org/10.1080/00949655.2012.668550</a>.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="diagnostische-modelle.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="anwendung.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["poisson-regression.pdf", "poisson-regression.tex", "poisson-regression.epub"],
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
